/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class AdminMainPanel extends javax.swing.JPanel {
    private boolean sbVisible = true;
    final Assignment frame;
    private OAdmin user;
    public LoginPanel loginPanel;
    public AAccountPanel accountPanel;
    
    
    /**
     * Creates new form CounselorMainPanel
     */
    public AdminMainPanel(Assignment frame, OAdmin user) {
        this.frame = frame;
        this.user = user;
        // create a method where u can read file and convert to object data
        initComponents();
        jLabel1.setText("Welcome "+user.getName());
        ImageIcon cmsIcon = new ImageIcon(getClass().getResource("/assignment/imgSrc/cms.png"));
        Image cms = cmsIcon.getImage();
        Image scaledCMS = cms.getScaledInstance(40, 50, Image.SCALE_SMOOTH);
        ImageIcon scaledCMSIcon = new ImageIcon(scaledCMS);
        JLabel iconLabel4 = new JLabel(scaledCMSIcon);
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(iconLabel4, BorderLayout.SOUTH);
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CMainPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        SideBarBut = new javax.swing.JButton();
        SideBarPanel = new javax.swing.JPanel();
        InnerSideBarPanel = new javax.swing.JPanel();
        AccBut = new javax.swing.JButton();
        StaffBut = new javax.swing.JButton();
        AppointBut = new javax.swing.JButton();
        ReportBut = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 82, 28));
        setForeground(new java.awt.Color(26, 82, 28));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(93, 158, 79));
        jLabel1.setText("Welcome");

        jButton1.setBackground(new java.awt.Color(26, 82, 28));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(93, 158, 79));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 158, 79));
        jLabel2.setText("CMS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        CMainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        CMainPanel.setAlignmentX(0.0F);
        CMainPanel.setAlignmentY(0.0F);
        CMainPanel.setPreferredSize(new java.awt.Dimension(1200, 730));
        CMainPanel.setLayout(new java.awt.BorderLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(850, 100));
        MainPanel.setLayout(new java.awt.BorderLayout());

        ContentPanel.setBackground(new java.awt.Color(102, 153, 0));
        ContentPanel.setPreferredSize(new java.awt.Dimension(800, 0));
        ContentPanel.setLayout(new java.awt.BorderLayout());
        MainPanel.add(ContentPanel, java.awt.BorderLayout.CENTER);

        SideBarBut.setBackground(new java.awt.Color(111, 148, 85));
        SideBarBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SideBarBut.setText("<");
        SideBarBut.setPreferredSize(new java.awt.Dimension(50, 23));
        SideBarBut.addActionListener(this::SideBarButActionPerformed);
        MainPanel.add(SideBarBut, java.awt.BorderLayout.WEST);

        CMainPanel.add(MainPanel, java.awt.BorderLayout.CENTER);

        SideBarPanel.setBackground(new java.awt.Color(111, 148, 85));
        SideBarPanel.setPreferredSize(new java.awt.Dimension(350, 100));
        SideBarPanel.setLayout(new java.awt.BorderLayout());

        InnerSideBarPanel.setBackground(new java.awt.Color(102, 153, 0));
        InnerSideBarPanel.setPreferredSize(new java.awt.Dimension(100, 300));
        InnerSideBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                InnerSideBarPanelMouseDragged(evt);
            }
        });
        InnerSideBarPanel.setLayout(new java.awt.GridLayout(0, 1));

        AccBut.setBackground(new java.awt.Color(111, 148, 85));
        AccBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccBut.setText("Manage user accounts");
        AccBut.addActionListener(this::AccButActionPerformed);
        InnerSideBarPanel.add(AccBut);

        StaffBut.setBackground(new java.awt.Color(111, 148, 85));
        StaffBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StaffBut.setText("Manage staff roster and schedules");
        StaffBut.setAlignmentY(0.0F);
        StaffBut.addActionListener(this::StaffButActionPerformed);
        InnerSideBarPanel.add(StaffBut);

        AppointBut.setBackground(new java.awt.Color(111, 148, 85));
        AppointBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AppointBut.setText("Monitor appointment statistics");
        AppointBut.addActionListener(this::AppointButActionPerformed);
        InnerSideBarPanel.add(AppointBut);

        ReportBut.setBackground(new java.awt.Color(111, 148, 85));
        ReportBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReportBut.setText("Generate reports");
        ReportBut.setActionCommand("");
        ReportBut.setAlignmentX(0.5F);
        ReportBut.addActionListener(this::ReportButActionPerformed);
        InnerSideBarPanel.add(ReportBut);

        SideBarPanel.add(InnerSideBarPanel, java.awt.BorderLayout.NORTH);

        CMainPanel.add(SideBarPanel, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void butHighlight(javax.swing.JButton but){
        ReportBut.setContentAreaFilled(false);
        AppointBut.setContentAreaFilled(false); 
        StaffBut.setContentAreaFilled(false);
        AccBut.setContentAreaFilled(false); 
        
        if(but.equals(ReportBut)){
            ReportBut.setContentAreaFilled(true);
        }
        if(but.equals(AppointBut)){
            AppointBut.setContentAreaFilled(true);
        }
        if(but.equals(StaffBut)){
            StaffBut.setContentAreaFilled(true);
        }
        if(but.equals(AccBut)){
            AccBut.setContentAreaFilled(true);
        }
    }
    
    private void SideBarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideBarButActionPerformed
        sbVisible = !sbVisible;
        SideBarPanel.setVisible(sbVisible);
        if(sbVisible == true){
            SideBarPanel.setPreferredSize(new java.awt.Dimension(350,0));
            SideBarBut.setText("<");
        }
        else{
            SideBarPanel.setPreferredSize(new java.awt.Dimension(0,0));
            SideBarBut.setText(">");
        }
        revalidate();
        repaint();
    }//GEN-LAST:event_SideBarButActionPerformed

    private void ReportButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButActionPerformed
        butHighlight(ReportBut);
        
    }//GEN-LAST:event_ReportButActionPerformed

    private void AppointButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointButActionPerformed
        butHighlight(AppointBut);
    }//GEN-LAST:event_AppointButActionPerformed

    private void StaffButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffButActionPerformed
        butHighlight(StaffBut);
    }//GEN-LAST:event_StaffButActionPerformed

    private void AccButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccButActionPerformed
        butHighlight(AccBut);
        accountPanel = new AAccountPanel();
        frame.switchContent(accountPanel, ContentPanel);
    }//GEN-LAST:event_AccButActionPerformed

    private void InnerSideBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerSideBarPanelMouseDragged

    }//GEN-LAST:event_InnerSideBarPanelMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginPanel = new LoginPanel(frame);
        frame.switchTo(loginPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccBut;
    private javax.swing.JButton AppointBut;
    private javax.swing.JPanel CMainPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel InnerSideBarPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ReportBut;
    private javax.swing.JButton SideBarBut;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JButton StaffBut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
