/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author User
 */
public class AStaffPanel extends javax.swing.JPanel {
    private DefaultTableModel model = new DefaultTableModel();
    private String[] columnName = {"AppointID", "CounselorUID", "StudentUID", "startDateTime", "endDateTime", "bookingType", "queueNumber", "status"};
    private int row = -1;
    final Assignment frame;
    private Calendar fT = null;
    private String fS = "All";

    /**
     * Creates new form AAccountPanel
     */
    public AStaffPanel(Assignment frame) {
        this.frame = frame;
        initComponents();
        model.setColumnIdentifiers(columnName);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter); 
        for(String line : Functions.readFile("appointment.txt")){
            if(!line.isEmpty()){
                String[] temp = line.split(",");
                model.addRow(temp);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StatusBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TimeBox = new javax.swing.JComboBox<>();
        Right = new javax.swing.JPanel();
        Bottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Top.setPreferredSize(new java.awt.Dimension(0, 50));

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(Top, java.awt.BorderLayout.NORTH);

        Left.setPreferredSize(new java.awt.Dimension(200, 0));

        jLabel1.setText("Filter status: ");

        StatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Confirmed", "Cancelled", "Done", "Pending" }));
        StatusBox.addActionListener(this::StatusBoxActionPerformed);

        jLabel2.setText("Filter Time:");

        TimeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Today", "This week", "This month" }));
        TimeBox.addActionListener(this::TimeBoxActionPerformed);

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(StatusBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeBox, 0, 149, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        add(Left, java.awt.BorderLayout.WEST);

        Right.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        add(Right, java.awt.BorderLayout.EAST);

        Bottom.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(Bottom, java.awt.BorderLayout.SOUTH);

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        row = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseReleased
    
    
    private void showRow(){
        model.setRowCount(0);
        Calendar today = Calendar.getInstance();
        today.set(Calendar.HOUR_OF_DAY,0);
        today.set(Calendar.MINUTE,0);
        today.set(Calendar.SECOND,0);
        for(String line : Functions.readFile("appointment.txt")){
            if(!line.isEmpty()){
                
                String[] temp = line.split(",");
                Calendar now = Functions.StringtoDateTime(temp[4]);
                if(fT!=null&&!fS.equals("All")){
                    if(now.after(today)&&now.before(fT)&&temp[7].equals(fS)){
                        model.addRow(temp);
                    }
                }
                else if(fT==null&&fS.equals("All")){
                    model.addRow(temp);
                }
                else if(fT!=null){
                    if(now.after(today)&&now.before(fT)){
                        model.addRow(temp);
                    }
                }
                else if(!fS.equals("All")){
                    if(temp[7].equals(fS)){
                        model.addRow(temp);
                    }
                }
            }
        }
    }
    private void StatusBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBoxActionPerformed
        fS = (String) StatusBox.getSelectedItem();
        showRow();
    }//GEN-LAST:event_StatusBoxActionPerformed

    private void TimeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeBoxActionPerformed
        int index = TimeBox.getSelectedIndex();
        Calendar target = Calendar.getInstance();
        switch(index){
            case 0 -> {
                target = null;
                break;
            }
            case 1 -> {
                target.set(Calendar.HOUR_OF_DAY, 23);
                target.set(Calendar.MINUTE, 59);
                target.set(Calendar.SECOND, 0);
                break;
            }
            case 2 -> {
                target.set(Calendar.HOUR_OF_DAY, 23);
                target.set(Calendar.MINUTE, 59);
                target.set(Calendar.SECOND, 0);
                target.add(Calendar.WEEK_OF_YEAR,1);
                break;
            }
            case 3 -> {
                target.set(Calendar.HOUR_OF_DAY, 23);
                target.set(Calendar.MINUTE, 59);
                target.set(Calendar.SECOND, 0);
                target.add(Calendar.MONTH,1);
                break;
            }
            
        }
        if(target != null){
            fT = (Calendar) target.clone();
        }
        else{
            fT = null;
        }
        showRow();
        
    }//GEN-LAST:event_TimeBoxActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JComboBox<String> StatusBox;
    private javax.swing.JComboBox<String> TimeBox;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
