/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CRecomPanel extends javax.swing.JPanel {

    private OCounselor user;
    private Assignment frame;
    
    public CRecomPanel(Assignment frame,OCounselor user) {
        this.frame = frame;
        this.user = user;
        initComponents();
        appointWarn.setVisible(false);
        recomWarn.setVisible(false);
        notesWarn.setVisible(false);
        studentBox.addItem("None");
        for(String line : Functions.readFile("loginData.txt")){
            if(line.split(",")[3].equals("Student")){
                studentBox.addItem(line.split(",")[1]);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        Bottom = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Center = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        appointBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        studentBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        recomArea = new javax.swing.JTextArea();
        saveBut = new javax.swing.JButton();
        appointWarn = new javax.swing.JLabel();
        notesWarn = new javax.swing.JLabel();
        recomWarn = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        Top.setPreferredSize(new java.awt.Dimension(848, 50));

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(Top, java.awt.BorderLayout.NORTH);

        Bottom.setPreferredSize(new java.awt.Dimension(848, 50));

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(Bottom, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        add(Right, java.awt.BorderLayout.EAST);

        Left.setPreferredSize(new java.awt.Dimension(100, 298));

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        add(Left, java.awt.BorderLayout.WEST);

        jLabel4.setText("Select an appointment:");

        jLabel5.setText("Consultation notes:");

        jLabel6.setText("Recomendation: ");

        jLabel1.setText("Filter appointment by student:");

        studentBox.addActionListener(this::studentBoxActionPerformed);

        noteArea.setColumns(20);
        noteArea.setRows(5);
        jScrollPane1.setViewportView(noteArea);

        recomArea.setColumns(20);
        recomArea.setRows(5);
        jScrollPane2.setViewportView(recomArea);

        saveBut.setText("Save note");
        saveBut.addActionListener(this::saveButActionPerformed);

        appointWarn.setForeground(new java.awt.Color(255, 0, 0));
        appointWarn.setText("Please select an appointment!");

        notesWarn.setForeground(new java.awt.Color(255, 0, 51));
        notesWarn.setText("Section cannot be empty!");

        recomWarn.setForeground(new java.awt.Color(255, 0, 0));
        recomWarn.setText("Section cannot be empty!");

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recomWarn)
                    .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(saveBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addGroup(CenterLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(119, 119, 119)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(studentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CenterLayout.createSequentialGroup()
                            .addComponent(appointBox, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(appointWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(notesWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(studentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointWarn))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(notesWarn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recomWarn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBut)
                .addGap(16, 16, 16))
        );

        add(Center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    private void showApp(String name){
        for(String line:Functions.readFile("appointment.txt")){
            String[] p = line.split(",");
            if(!p[1].equals(user.getId())){
                continue;
            }
            if(!p[7].equals("Done")){
                continue;
            }
            if(Functions.appointmentInNotes().contains(p[0])){
                continue;
            }
            if(name.equals("None")||name.equals(Functions.filterID(p[2], "userData.txt").split(",")[1])){
                String data = p[0]+"--"+Functions.filterID(p[2], "userData.txt").split(",")[1]+"--"+p[3];
                appointBox.addItem(data);
            }
            
        }
    }
    
    private void studentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBoxActionPerformed
        String stuName = (String) studentBox.getSelectedItem();
        appointBox.removeAllItems();
        showApp(stuName);
    }//GEN-LAST:event_studentBoxActionPerformed

    private void saveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButActionPerformed
        if(appointBox.getSelectedItem()==null){appointWarn.setVisible(true);return;}
        if(recomArea.getText().trim().isEmpty()){recomWarn.setVisible(true);return;}
        if(noteArea.getText().trim().isEmpty()){notesWarn.setVisible(true);return;}
        String temp = (String)appointBox.getSelectedItem();
        String data = temp.split("--")[0]+"|"+user.getId()+"|"+temp.split("--")[1]+"|"+temp.split("--")[2]+"|"+noteArea.getText()+"|"+recomArea.getText();
        Functions.inputFile("note.txt", data, "append");
        appointBox.removeItem(temp);
        JOptionPane.showMessageDialog(frame, "Successfully added note!");
    }//GEN-LAST:event_saveButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private javax.swing.JComboBox<String> appointBox;
    private javax.swing.JLabel appointWarn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea noteArea;
    private javax.swing.JLabel notesWarn;
    private javax.swing.JTextArea recomArea;
    private javax.swing.JLabel recomWarn;
    private javax.swing.JButton saveBut;
    private javax.swing.JComboBox<String> studentBox;
    // End of variables declaration//GEN-END:variables
}
