/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package assignment;

import java.util.ArrayList;
import java.util.Calendar;
/**
 * Appointment class - represents a counselling appointment/booking.
 * This is the CORE class for the Receptionist module:
 * - Create / Update / Cancel appointments
 * - Assign counselor
 * - Generate queue number
 * - Handle Walk-in / Online booking types
 */
public class OAppointment {

    // ===== Attributes =====
    private String appointmentId;   // e.g. "A001"
    private String studentId;       // link to student (just the ID, not the whole Student object)
    private String counselorId;     // assigned by receptionist, can be empty at first
    private Calendar startTime;            // format: yyyy-MM-dd
    private Calendar endTime;            // format: HH:mm
    private String bookingType;     // "Walk-in" or "Online"
    private String status;          // "Pending" / "Confirmed" / "Cancelled" / "Completed"
    private int queueNumber;        // generated by receptionist

    // ===== Constructors =====

    public OAppointment(String appointmentId, String counselorId, String studentId,
                        Calendar startTime, Calendar endTime, String bookingType, int queueNumber, String status) {
        this.appointmentId = appointmentId;
        this.studentId = studentId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.bookingType = bookingType;
        this.status = status;
        this.counselorId = counselorId;
        this.queueNumber = queueNumber;
    }

    // ===== Getters and Setters =====
    public String getAppointmentId() {return appointmentId;}
    public String getCounselorId() {return counselorId;}
    public String getStudentId() {return studentId;}
    public Calendar getStartTime(){return startTime;}
    public Calendar getEndTime(){return endTime;}
    public String getBookingType(){return bookingType;}
    public int getQueueNumber(){return queueNumber;}
    public String getStatus(){return status;}
    
    public void setAppointmentId(){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("appointment.txt"),"B",0);
        int max = 0;
        for(String line : lines){
            String[] p = line.split(",");
            int idNum = Integer.parseInt(p[0].substring(1));
            if((this.studentId.equals(p[2])||this.counselorId.equals(p[2]))&&this.startTime.equals(Functions.StringtoDateTime(p[3]))){
                System.out.println("Debug: Appointment exists!");
                return;
            }
            if(idNum > max){
                max = idNum;
            }
        }
        this.appointmentId = "B"+String.format("%06d", max+1);
    }
    
    public void setCounselorId(String counselorId){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("userData.txt"),"C",0);
        for(String line: lines){
            String tempId = line.split(",")[0];
            if(counselorId.equals(tempId)){
                this.counselorId = counselorId;
                return;
            }
        }
    }
    
    public void setStudentId(String studentId){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("userData.txt"),"S",0);
        for(String line: lines){
            String tempId = line.split(",")[0];
            if(studentId.equals(tempId)){
                this.studentId = studentId;
                return;
            }
        }
    }
    
    // set date and stuff
    

    /**
     * Assigns a counselor to this appointment.
     * This IS the "Assign counselor to appointments" requirement.
     */
    public void assignCounselor(String counselorId) {
        this.counselorId = counselorId;
        this.status = "Approved";
    }

    /**
     * Cancels this appointment.
     */
    public void cancelAppointment() {
        this.status = "Cancelled";
    }

    /**
     * Converts this Appointment into one line of text for appointments.txt
     * Format: id|studentId|studentName|counselorId|counselorName|date|time|bookingType|status|queueNumber
     */
    public String toFileString() {
        return appointmentId + "," + counselorId + "," + studentId + ","
                + Functions.DateTimetoString(startTime) + "," + Functions.DateTimetoString(endTime) + "," + bookingType + "," + queueNumber + "," + status ;
    }

    /**
     * Creates an Appointment object from one line of text read from appointments.txt
     */
    public static OAppointment fromFileString(String line) {
        String[] p = line.split(",");
        return new OAppointment(
        p[0],p[1],p[2],Functions.StringtoDateTime(p[3]),Functions.StringtoDateTime(p[4]),p[5],Integer.parseInt(p[6]),p[7]);
    }

    
}
