/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package assignment;

import java.util.ArrayList;
import java.util.Calendar;

/**
 * Appointment class - represents a counselling appointment/booking.
 * This is the CORE class for the Receptionist module:
 * - Create / Update / Cancel appointments
 * - Assign counselor
 * - Generate queue number
 * - Handle Walk-in / Online booking types
 */
public class OAppointment {

    // ===== Attributes =====
    private String appointmentId;   // e.g. "A001"
    private String studentId;       // link to student (just the ID, not the whole Student object)
    private String studentName;     // store name directly too, so Receptionist UI doesn't need Student class
    private String counselorId;     // assigned by receptionist, can be empty at first
    private String counselorName;
    private Calendar startTime;
    private Calendar endTime;
    private String bookingType;     // "WalkIn" or "Online"
    private String status;          // (Approved, Declined, PendingAdd, PendingDelete, PendingUpdate, Done)
    private int queueNumber;        // generated by receptionist, null for online

    // ===== Constructors =====

    public OAppointment() {
        this.status = "Pending";
    }

    public OAppointment(String appointmentId, String counselorId, String studentId, Calendar startTime, Calendar endTime, String bookingType, String status, int queueNumber) {
        this.appointmentId = appointmentId;
        this.counselorId = counselorId;
        this.studentId = studentId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.bookingType = bookingType;
        this.status = status;
        this.queueNumber = queueNumber; // 0 means not assigned yet
    }

    // ===== Getters and Setters =====
    public String getAppointmentId(){ return this.appointmentId; }
    public String getCounselorId(){ return this.counselorId; }
    public String getStudentId(){ return this.studentId; }
    public Calendar getStartTime(){ return this.startTime; }
    public Calendar getEndTime(){ return this.endTime; }
    public String getBookingType(){ return this.bookingType; }
    public String getStatus(){ return this.status; }
    public int getQueueNumber(){ return this.queueNumber; }
    
    public void setAppointmentId(){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("appointment.txt"),"B",0);
        int max = 0;
        for(String line : lines){
            String[] p = line.split(",");
            int idNum = Integer.parseInt(p[0].substring(1));
            if(idNum > max){
                max = idNum;
            }
        }
        this.appointmentId = "B"+String.format("%06d", max+1);
    }
    
    public void setCounselorId(String counselorId){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("userData.txt"),"C",0);
        for(String line: lines){
            String tempId = line.split(",")[0];
            if(counselorId.equals(tempId)){
                this.counselorId = counselorId;
                return;
            }
        }
    }
    
    public void setStudentId(String studentId){
        ArrayList<String> lines = Functions.filterData(Functions.readFile("userData.txt"),"S",0);
        for(String line: lines){
            String tempId = line.split(",")[0];
            if(studentId.equals(tempId)){
                this.studentId = studentId;
                return;
            }
        }
    }
    
    public void setStartTime(Calendar startTime){
        
    }

    /**
     * Assigns a counselor to this appointment.
     * This IS the "Assign counselor to appointments" requirement.
     */
    public void assignCounselor(String counselorId, String counselorName) {
        this.counselorId = counselorId;
        this.counselorName = counselorName;
        this.status = "Confirmed";
    }

    /**
     * Cancels this appointment.
     */
    public void cancelAppointment() {
        this.status = "Cancelled";
    }

    /**
     * Converts this Appointment into one line of text for appointments.txt
     * Format: id|studentId|studentName|counselorId|counselorName|date|time|bookingType|status|queueNumber
     */
    public String toFileString() {
        return appointmentId + "|" + studentId + "|" + studentName + "|"
                + counselorId + "|" + counselorName + "|" + date + "|" + time + "|"
                + bookingType + "|" + status + "|" + queueNumber;
    }

    /**
     * Creates an Appointment object from one line of text read from appointments.txt
     */
    public static OAppointment fromFileString(String line) {
        String[] parts = line.split(",");
        OAppointment a = new OAppointment();
        a.setAppointmentId(parts[0]);
        a.setStudentId(parts[1]);
        a.setStudentName(parts[2]);
        a.setCounselorId(parts[3]);
        a.setCounselorName(parts[4]);
        a.setDate(parts[5]);
        a.setTime(parts[6]);
        a.setBookingType(parts[7]);
        a.setStatus(parts[8]);
        a.setQueueNumber(Integer.parseInt(parts[9]));
        return a;
    }

    @Override
    public String toString() {
        return appointmentId + " - " + studentName + " (" + date + " " + time + ")";
    }
}
