/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class ReceptionistMainPanel extends javax.swing.JPanel {
    private boolean sbVisible = true;
    final Assignment frame;
    private OReceptionist user;
    public LoginPanel loginPanel;
    public RAccountPanel accPanel;
    public RAppointPanel appPanel;
    public RAssignPanel assPanel;
    public RQueuePanel queuePanel;
    public UpdatePanel upPanel;
    
    
    /**
     * Creates new form CounselorMainPanel
     */
    public ReceptionistMainPanel(Assignment frame, OReceptionist user) {
        this.frame = frame;
        this.user = user;
        // create a method where u can read file and convert to object data
        initComponents();
        Welcome.setText("Welcome "+user.getName());
        
        ImageIcon dark = new ImageIcon(getClass().getResource("/assignment/imgSrc/dark.png"));
        dark.setDescription("dark");
        jLabel1.setIcon(dark);
        
        ImageIcon cmsIcon = new ImageIcon(getClass().getResource("/assignment/imgSrc/cms.png"));
        Image cms = cmsIcon.getImage();
        Image scaledCMS = cms.getScaledInstance(40, 50, Image.SCALE_SMOOTH);
        ImageIcon scaledCMSIcon = new ImageIcon(scaledCMS);
        JLabel iconLabel4 = new JLabel(scaledCMSIcon);
        Logo.setLayout(new BorderLayout());
        Logo.add(iconLabel4, BorderLayout.SOUTH);
        Logo.revalidate();
        Logo.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopNavBar = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        LogoText = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        CMainPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        SideBarBut = new javax.swing.JButton();
        SideBarPanel = new javax.swing.JPanel();
        InnerSideBarPanel = new javax.swing.JPanel();
        accBut = new javax.swing.JButton();
        appBut = new javax.swing.JButton();
        assBut = new javax.swing.JButton();
        queueBut = new javax.swing.JButton();
        upBut = new javax.swing.JButton();
        TaskBar = new javax.swing.JPanel();
        GitHub = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 102, 0));
        setForeground(new java.awt.Color(26, 82, 28));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        TopNavBar.setBackground(new java.awt.Color(102, 153, 0));
        TopNavBar.setAlignmentX(0.0F);
        TopNavBar.setAlignmentY(0.0F);
        TopNavBar.setOpaque(false);
        TopNavBar.setPreferredSize(new java.awt.Dimension(0, 65));
        TopNavBar.setLayout(new java.awt.BorderLayout());

        Left.setOpaque(false);
        Left.setPreferredSize(new java.awt.Dimension(120, 0));

        Logo.setOpaque(false);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        LogoText.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        LogoText.setForeground(new java.awt.Color(93, 158, 79));
        LogoText.setText("CMS");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TopNavBar.add(Left, java.awt.BorderLayout.WEST);

        Right.setOpaque(false);
        Right.setPreferredSize(new java.awt.Dimension(100, 0));

        Logout.setBackground(new java.awt.Color(0, 153, 51));
        Logout.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(this::LogoutActionPerformed);

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TopNavBar.add(Right, java.awt.BorderLayout.EAST);

        Center.setOpaque(false);
        Center.setPreferredSize(new java.awt.Dimension(100, 0));

        Welcome.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(93, 158, 79));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome");
        Welcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(Welcome)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TopNavBar.add(Center, java.awt.BorderLayout.CENTER);

        add(TopNavBar, java.awt.BorderLayout.NORTH);

        CMainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        CMainPanel.setAlignmentX(0.0F);
        CMainPanel.setAlignmentY(0.0F);
        CMainPanel.setPreferredSize(new java.awt.Dimension(1200, 730));
        CMainPanel.setLayout(new java.awt.BorderLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setAlignmentX(0.0F);
        MainPanel.setAlignmentY(0.0F);
        MainPanel.setOpaque(false);
        MainPanel.setPreferredSize(new java.awt.Dimension(850, 100));
        MainPanel.setLayout(new java.awt.BorderLayout());

        ContentPanel.setOpaque(false);
        ContentPanel.setPreferredSize(new java.awt.Dimension(800, 0));
        ContentPanel.setLayout(new java.awt.BorderLayout());
        MainPanel.add(ContentPanel, java.awt.BorderLayout.CENTER);

        SideBarBut.setBackground(new java.awt.Color(111, 148, 85));
        SideBarBut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SideBarBut.setText("<");
        SideBarBut.setBorder(null);
        SideBarBut.setPreferredSize(new java.awt.Dimension(50, 23));
        SideBarBut.addActionListener(this::SideBarButActionPerformed);
        MainPanel.add(SideBarBut, java.awt.BorderLayout.WEST);

        CMainPanel.add(MainPanel, java.awt.BorderLayout.CENTER);

        SideBarPanel.setBackground(new java.awt.Color(111, 148, 85));
        SideBarPanel.setAlignmentX(0.0F);
        SideBarPanel.setAlignmentY(0.0F);
        SideBarPanel.setPreferredSize(new java.awt.Dimension(350, 100));
        SideBarPanel.setLayout(new java.awt.BorderLayout());

        InnerSideBarPanel.setBackground(new java.awt.Color(102, 153, 0));
        InnerSideBarPanel.setPreferredSize(new java.awt.Dimension(100, 300));
        InnerSideBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                InnerSideBarPanelMouseDragged(evt);
            }
        });
        InnerSideBarPanel.setLayout(new java.awt.GridLayout(0, 1));

        accBut.setBackground(new java.awt.Color(111, 148, 85));
        accBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        accBut.setText("Manage student accounts ");
        accBut.setBorder(null);
        accBut.setContentAreaFilled(false);
        accBut.addActionListener(this::accButActionPerformed);
        InnerSideBarPanel.add(accBut);

        appBut.setBackground(new java.awt.Color(111, 148, 85));
        appBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        appBut.setText("Manage appointments");
        appBut.setAlignmentY(0.0F);
        appBut.setBorder(null);
        appBut.setContentAreaFilled(false);
        appBut.addActionListener(this::appButActionPerformed);
        InnerSideBarPanel.add(appBut);

        assBut.setBackground(new java.awt.Color(111, 148, 85));
        assBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        assBut.setText("Assign counselor to appointments ");
        assBut.setBorder(null);
        assBut.setContentAreaFilled(false);
        assBut.addActionListener(this::assButActionPerformed);
        InnerSideBarPanel.add(assBut);

        queueBut.setBackground(new java.awt.Color(111, 148, 85));
        queueBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        queueBut.setText("Generate queue numbers");
        queueBut.setActionCommand("");
        queueBut.setAlignmentX(0.5F);
        queueBut.setBorder(null);
        queueBut.setContentAreaFilled(false);
        queueBut.addActionListener(this::queueButActionPerformed);
        InnerSideBarPanel.add(queueBut);

        upBut.setBackground(new java.awt.Color(111, 148, 85));
        upBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        upBut.setText("Update Profile");
        upBut.setBorder(null);
        upBut.setContentAreaFilled(false);
        upBut.addActionListener(this::upButActionPerformed);
        InnerSideBarPanel.add(upBut);

        SideBarPanel.add(InnerSideBarPanel, java.awt.BorderLayout.NORTH);

        CMainPanel.add(SideBarPanel, java.awt.BorderLayout.WEST);

        add(CMainPanel, java.awt.BorderLayout.CENTER);

        TaskBar.setOpaque(false);
        TaskBar.setPreferredSize(new java.awt.Dimension(0, 50));

        GitHub.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/imgSrc/github.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout GitHubLayout = new javax.swing.GroupLayout(GitHub);
        GitHub.setLayout(GitHubLayout);
        GitHubLayout.setHorizontalGroup(
            GitHubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GitHubLayout.setVerticalGroup(
            GitHubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/imgSrc/dark.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout TaskBarLayout = new javax.swing.GroupLayout(TaskBar);
        TaskBar.setLayout(TaskBarLayout);
        TaskBarLayout.setHorizontalGroup(
            TaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1087, Short.MAX_VALUE)
                .addComponent(GitHub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TaskBarLayout.setVerticalGroup(
            TaskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GitHub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(TaskBar, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    private void butHighlight(javax.swing.JButton but){
        queueBut.setContentAreaFilled(false);
        accBut.setContentAreaFilled(false); 
        appBut.setContentAreaFilled(false);
        assBut.setContentAreaFilled(false); 
        upBut.setContentAreaFilled(false); 
        
        if(but.equals(queueBut)){
            queueBut.setContentAreaFilled(true);
        }
        if(but.equals(accBut)){
            accBut.setContentAreaFilled(true);
        }
        if(but.equals(appBut)){
            appBut.setContentAreaFilled(true);
        }
        if(but.equals(assBut)){
            assBut.setContentAreaFilled(true);
        }
        if(but.equals(upBut)){
            upBut.setContentAreaFilled(true);
        }
    }
    
    private void SideBarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideBarButActionPerformed
        sbVisible = !sbVisible;
        SideBarPanel.setVisible(sbVisible);
        if(sbVisible == true){
            SideBarPanel.setPreferredSize(new java.awt.Dimension(350,0));
            SideBarBut.setText("<");
        }
        else{
            SideBarPanel.setPreferredSize(new java.awt.Dimension(0,0));
            SideBarBut.setText(">");
        }
        revalidate();
        repaint();
    }//GEN-LAST:event_SideBarButActionPerformed

    private void queueButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueButActionPerformed
        butHighlight(queueBut);
        queuePanel = new RQueuePanel();
        frame.switchContent(queuePanel, ContentPanel);
    }//GEN-LAST:event_queueButActionPerformed

    private void accButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accButActionPerformed
        butHighlight(accBut);
        accPanel = new RAccountPanel(frame);
        frame.switchContent(accPanel, ContentPanel);
    }//GEN-LAST:event_accButActionPerformed

    private void appButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appButActionPerformed
        butHighlight(appBut);
        appPanel = new RAppointPanel(frame);
        frame.switchContent(appPanel, ContentPanel);
    }//GEN-LAST:event_appButActionPerformed

    private void assButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assButActionPerformed
        butHighlight(assBut);
        assPanel = new RAssignPanel(frame);
        frame.switchContent(assPanel, ContentPanel);
    }//GEN-LAST:event_assButActionPerformed

    private void InnerSideBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerSideBarPanelMouseDragged

    }//GEN-LAST:event_InnerSideBarPanelMouseDragged

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        loginPanel = new LoginPanel(frame);
        frame.switchTo(loginPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/oggyng/Java-Ass-ignment"));
        } catch (Exception e) {
            System.out.println("Cannot open: " + e.getMessage());
        }
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        try {
            String current = ((ImageIcon) jLabel1.getIcon()).getDescription();
            if(current.equals("light")) {
                UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
                ImageIcon dark = new ImageIcon(getClass().getResource("/assignment/imgSrc/dark.png"));
                dark.setDescription("dark");
                jLabel1.setIcon(dark);
            } else {
                UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
                ImageIcon light = new ImageIcon(getClass().getResource("/assignment/imgSrc/light.png"));
                light.setDescription("light");
                jLabel1.setIcon(light);
            }
            SwingUtilities.updateComponentTreeUI(frame);
        } catch(Exception e) {
            System.out.println("eror");
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    private void upButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButActionPerformed
        butHighlight(upBut);
        upPanel = new UpdatePanel(frame,user);
        frame.switchContent(upPanel, ContentPanel);
    }//GEN-LAST:event_upButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CMainPanel;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel GitHub;
    private javax.swing.JPanel InnerSideBarPanel;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel LogoText;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Right;
    private javax.swing.JButton SideBarBut;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JPanel TaskBar;
    private javax.swing.JPanel TopNavBar;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton accBut;
    private javax.swing.JButton appBut;
    private javax.swing.JButton assBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton queueBut;
    private javax.swing.JButton upBut;
    // End of variables declaration//GEN-END:variables
}
