/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

/**
 *
 * @author User
 */
public class SProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ARecomPanel
     */
    public SProfilePanel() {
        initComponents();
        for(String line:Functions.readFile("userData.txt")){
            String[] p = line.split(",");
            if(p[0].substring(0,1).equals("C")){
                counBox.addItem(Functions.filterID(p[0], "userData.txt").split(",")[1]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Center = new javax.swing.JPanel();
        counBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monBox = new javax.swing.JCheckBox();
        tueBox = new javax.swing.JCheckBox();
        wedBox = new javax.swing.JCheckBox();
        thuBox = new javax.swing.JCheckBox();
        friBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        specField = new javax.swing.JTextField();
        Right = new javax.swing.JPanel();
        Bottom = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        Top.setMinimumSize(new java.awt.Dimension(0, 25));
        Top.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(Top, java.awt.BorderLayout.NORTH);

        Left.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        add(Left, java.awt.BorderLayout.WEST);

        counBox.addActionListener(this::counBoxActionPerformed);

        jLabel1.setText("Choose a counselor:");

        jLabel2.setText("Available Day:");

        monBox.setText("Monday");

        tueBox.setText("Tuesday");

        wedBox.setText("Wednesday");

        thuBox.setText("Thursday");

        friBox.setText("Friday");

        jLabel3.setText("Specialism:");

        specField.setEditable(false);
        specField.addActionListener(this::specFieldActionPerformed);

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(friBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thuBox)
                    .addComponent(wedBox)
                    .addComponent(tueBox)
                    .addComponent(monBox)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(counBox, 0, 147, Short.MAX_VALUE)
                    .addComponent(specField))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tueBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wedBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thuBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friBox)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        add(Center, java.awt.BorderLayout.CENTER);

        Right.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        add(Right, java.awt.BorderLayout.EAST);

        Bottom.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(Bottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void specFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specFieldActionPerformed

    private void counBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counBoxActionPerformed
        if(counBox.getSelectedItem()==null){return;}
        String coun = (String) counBox.getSelectedItem();
        String id = Functions.filterName(coun, "userData.txt").split(",")[0];
        String[] data = Functions.filterID(id, "cProfile.txt").split(",");
        monBox.setSelected(Boolean.parseBoolean(data[1]));
        tueBox.setSelected(Boolean.parseBoolean(data[2]));
        wedBox.setSelected(Boolean.parseBoolean(data[3]));
        thuBox.setSelected(Boolean.parseBoolean(data[4]));
        friBox.setSelected(Boolean.parseBoolean(data[5]));
        specField.setText(data[6]);
    }//GEN-LAST:event_counBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private javax.swing.JComboBox<String> counBox;
    private javax.swing.JCheckBox friBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox monBox;
    private javax.swing.JTextField specField;
    private javax.swing.JCheckBox thuBox;
    private javax.swing.JCheckBox tueBox;
    private javax.swing.JCheckBox wedBox;
    // End of variables declaration//GEN-END:variables
}
