/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdatePanel extends javax.swing.JPanel {
    private ORoleParent user;
    private char pwChar;
    private Assignment frame;
    private String role;
    /**
     * Creates new form ARecomPanel
     */
    public UpdatePanel(Assignment frame, ORoleParent user) {
        this.frame = frame;
        this.user = user;
        this.role = Functions.filterID(user.getId(), "loginData.txt").split(",")[3];
        initComponents();
        pwChar = PassField.getEchoChar();
        eName.setVisible(false);
        eMail.setVisible(false);
        ePass.setVisible(false);
        eCPass.setVisible(false);
        if(role.equals("Counselor")){
            counPanel.setVisible(true);
        }
        else{
            counPanel.setVisible(false);
        }
        NameField.setText(user.getName());
        MailField.setText(user.getEmail());
        PassField.setText(Functions.filterID(user.getId(), "loginData.txt").split(",")[2]);
        CPassField.setText(Functions.filterID(user.getId(), "loginData.txt").split(",")[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        Center = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        CPassField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MailField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        eName = new javax.swing.JLabel();
        eMail = new javax.swing.JLabel();
        ePass = new javax.swing.JLabel();
        eCPass = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        counPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        specBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        mon = new javax.swing.JCheckBox();
        tue = new javax.swing.JCheckBox();
        wed = new javax.swing.JCheckBox();
        thu = new javax.swing.JCheckBox();
        fri = new javax.swing.JCheckBox();
        eDay = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        Top.setMinimumSize(new java.awt.Dimension(0, 55));
        Top.setPreferredSize(new java.awt.Dimension(0, 105));

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        add(Top, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Name:");

        jLabel2.setText("Password: ");

        jLabel3.setText("Confirm Password:");

        jLabel4.setText("Email:");

        MailField.addActionListener(this::MailFieldActionPerformed);

        jButton1.setText("Update Profile");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        eName.setForeground(new java.awt.Color(255, 0, 51));
        eName.setText("*Name Field cannot be empty!");

        eMail.setForeground(new java.awt.Color(255, 0, 51));
        eMail.setText("*Email Field cannot be empty!");

        ePass.setForeground(new java.awt.Color(255, 0, 0));
        ePass.setText("*Password Field cannot be empty!");

        eCPass.setForeground(new java.awt.Color(255, 0, 0));
        eCPass.setText("*This Field cannot be empty!");

        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        jLabel5.setText("Specialism: ");

        specBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Career", "Personal", "Financial", "Mental Health" }));

        jLabel6.setText("Available Days: ");

        mon.setText("Monday");

        tue.setText("Tuesday");

        wed.setText("Wednesday");

        thu.setText("Thursday");

        fri.setText("Friday");

        eDay.setForeground(new java.awt.Color(255, 0, 0));
        eDay.setText("*Please select at least one day");

        javax.swing.GroupLayout counPanelLayout = new javax.swing.GroupLayout(counPanel);
        counPanel.setLayout(counPanelLayout);
        counPanelLayout.setHorizontalGroup(
            counPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(counPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(specBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(mon)
                    .addComponent(tue)
                    .addComponent(wed)
                    .addComponent(thu)
                    .addComponent(fri)
                    .addComponent(eDay))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        counPanelLayout.setVerticalGroup(
            counPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eDay)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CenterLayout = new javax.swing.GroupLayout(Center);
        Center.setLayout(CenterLayout);
        CenterLayout.setHorizontalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPassField)
                    .addComponent(MailField)
                    .addComponent(PassField)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jCheckBox1)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eName)
                    .addComponent(eMail)
                    .addComponent(ePass)
                    .addComponent(eCPass))
                .addGap(57, 57, 57)
                .addComponent(counPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CenterLayout.setVerticalGroup(
            CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(counPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CenterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CenterLayout.createSequentialGroup()
                                .addComponent(eName)
                                .addGap(40, 40, 40)
                                .addComponent(eMail)
                                .addGap(40, 40, 40)
                                .addComponent(ePass)
                                .addGap(40, 40, 40)
                                .addComponent(eCPass))
                            .addGroup(CenterLayout.createSequentialGroup()
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(Center, java.awt.BorderLayout.CENTER);

        Bottom.setPreferredSize(new java.awt.Dimension(0, 105));

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        add(Bottom, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void MailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eCPass.setText("*This Field cannot be empty!");
        eName.setVisible(false);
        eMail.setVisible(false);
        ePass.setVisible(false);
        eCPass.setVisible(false);
        eDay.setVisible(false);
        
        if(NameField.getText().length()==0){eName.setVisible(true);return;}
        if(MailField.getText().length()==0){eMail.setVisible(true);return;}
        if(PassField.getPassword().length==0){ePass.setVisible(true);return;}
        if(CPassField.getPassword().length==0){eCPass.setVisible(true);return;}
        if(role.equals("Counselor")){
            if(!mon.isSelected()&&!tue.isSelected()&&!wed.isSelected()&&!thu.isSelected()&&!fri.isSelected()){
                eDay.setVisible(true);
                return;
            }
        }
        
        String pass = new String(PassField.getPassword());
        String cpass = new String(CPassField.getPassword());
        if(!pass.equals(cpass)){
            eCPass.setText("*Password does not match!");
            eCPass.setVisible(true);
            return;
        }
        
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to update?")==0){
            String name = NameField.getText().trim();
            String mail = MailField.getText().trim();
            
            String loginTxt = user.getId()+","+name+","+pass+","+role;
            user.setName(name);
            user.setEmail(mail);
            Functions.removeData(user.getId(), "loginData.txt");
            Functions.removeData(user.getId(), "userData.txt");
            user.initData();
            Functions.inputFile("loginData.txt", loginTxt, "append");
            if(role.equals("Counselor")){
                String cProTxt = user.getId()+","+ Boolean.toString(mon.isSelected())+","+Boolean.toString(tue.isSelected())+","+Boolean.toString(wed.isSelected())+","+Boolean.toString(thu.isSelected())+","+Boolean.toString(fri.isSelected())+","+specBox.getSelectedItem();
                System.out.println(cProTxt);
            }
            JOptionPane.showMessageDialog(frame,"Profile updated successfully!");
            
        }
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            PassField.setEchoChar((char)0);
            CPassField.setEchoChar((char)0);
        }
        else{
            PassField.setEchoChar(pwChar);
            CPassField.setEchoChar(pwChar);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPasswordField CPassField;
    private javax.swing.JPanel Center;
    private javax.swing.JTextField MailField;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JPanel Top;
    private javax.swing.JPanel counPanel;
    private javax.swing.JLabel eCPass;
    private javax.swing.JLabel eDay;
    private javax.swing.JLabel eMail;
    private javax.swing.JLabel eName;
    private javax.swing.JLabel ePass;
    private javax.swing.JCheckBox fri;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox mon;
    private javax.swing.JComboBox<String> specBox;
    private javax.swing.JCheckBox thu;
    private javax.swing.JCheckBox tue;
    private javax.swing.JCheckBox wed;
    // End of variables declaration//GEN-END:variables
}
